// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgrlbhegvxqszwlllrwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndncmxiaGVndnhxc3p3bGxscndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzcyMDcsImV4cCI6MjA2MTY1MzIwN30.e1prPXOSbqFo8xEPQF2eTp_ItmGIPMI-bu5m60WC-GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);